### ISSUE TITLE
Throws unexpected error at : instance/monitoring

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/gravitee-docker#3]
_From @Tony-Proum on May 13, 2016 9:58_

Hi,

I got an Unexpected Error when trying to see instance monitoring screen. According to management api logs, It'seems this error is due to a downtime of my elasticsearch cluster.

I guess that the error should be more explicite.

see attached files to see error log

[RestApi.txt](https://github.com/gravitee-io/gravitee-management-rest-api/files/262950/RestApi.txt)

_Copied from original issue: gravitee-io/gravitee-management-rest-api#77_

**Comment by brasseld** [comment]
Hi @Tony-Proum,

According to your log, you're using our Docker containers.
Is the elasticsearch container really down ?

**Comment by brasseld** [comment]
_From @Tony-Proum on May 13, 2016 13:41_

Yes I used gravitee containers linked with own elasticsearch container, In my first post, I thought the link between gravitee management api and ES was broken. According to api logs, It's seems to request ES on the wrong container address : I can't figure out why org.elasticsearch.client.transport try to reach elasticsearch on **mongo**/10.7.0.26:**9300**

ES container is running, but gravitee api request is a mix between environment variables : 
    - ES_HOST=elasticsearch
    - ES_PORT=**9300**
    - MONGO_HOST=**mongo**
    - MONGO_PORT=27017
I got the right port, but the wrong host. Do you think that I should open a second issue in gravitee-docker project ?

**Comment by NicolasGeraud** [comment]
hi @Tony-Proum, 

can you exec bash into your gateway container and copy here your gravitee.yml ?

This file is in ${GRAVITEEIO_HOME}/config/gravitee.yml.

I think you're using the ''issue/#1-update.docker.images'' branch. I use sed to modify the config file (https://github.com/gravitee-io/gravitee-docker/blob/issue/%231-update.docker.images/images/gateway/entrypoint.sh) and there is probably a bug ...

**Comment by Tony-Proum** [comment]
hi @NicolasGeraud 

Yes, I'm using a fork of gravitee-docker project, I'm facing an issue when building a container from the branch called ''issue/#1-update.docker.images' (with docker-cloud) so I had to create a new branch without any "/". You can find this new branch at https://github.com/ChezTone/gravitee-docker/tree/docker 

You can see [gravitee.txt](https://github.com/gravitee-io/gravitee-docker/files/269046/gravitee.txt) extracted from the running docker

**Comment by NicolasGeraud** [comment]
I think i got it.
in https://github.com/ChezTone/gravitee-docker/blob/docker/images/management-api/entrypoint.sh can you change 
```
sed -i s/"host: ${MONGO_DEFAULT_HOST}"/"host: ${MONGO_HOST}"/ ${GRAVITEEIO_HOME}/config/gravitee.yml
sed -i s/"port: ${MONGO_DEFAULT_PORT}"/"port: ${MONGO_PORT}"/ ${GRAVITEEIO_HOME}/config/gravitee.yml
```
with
```
   sed -i 146s/"host: ${ES_DEFAULT_HOST}"/"host: ${ES_HOST}"/ ${GRAVITEEIO_HOME}/config/gravitee.yml
   sed -i 147s/"port: ${ES_DEFAULT_PORT}"/"port: ${ES_PORT}"/ ${GRAVITEEIO_HOME}/config/gravitee.yml

   sed -i 143s/"host: ${MONGO_DEFAULT_HOST}"/"host: ${MONGO_HOST}"/ ${GRAVITEEIO_HOME}/config/gravitee.yml
   sed -i 144s/"port: ${MONGO_DEFAULT_PORT}"/"port: ${MONGO_PORT}"/ ${GRAVITEEIO_HOME}/config/gravitee.yml
``
?

**Comment by NicolasGeraud** [comment]
And add 
```
ENV ES_DEFAULT_HOST localhost
ENV ES_DEFAULT_PORT 9300
ENV ES_HOST localhost
ENV ES_PORT 9300
```
in
https://github.com/ChezTone/gravitee-docker/blob/docker/images/management-api/Dockerfile

**Comment by Tony-Proum** [comment]
Can't figure out why : now the mongodb connexion failed. MongoDb seems to be available from other container . I started a mongo container and connect it to the db and I can see the gravitee database but the management api throws an error.

Maybe my docker-compose file is corrupted. I will investigate this way after work.

**Comment by NicolasGeraud** [comment]
check your gravitee.yml inside the gateway container and the management-api container. At the bottom of the file you must have a configuration for the mongodb and elasticsearch connection.

This yaml is modified at runtime by the entrypoint, based on the environment variables provided in the Dockerfile.

**Comment by Tony-Proum** [comment]
Ok, thanks for the explanations, the last commit fix the problem. In the "docker" branche, I used version 0.12.0 of gravitee-management-api and I think the gravitee.yml file has changed since version 0 so I have to change the lines number used for sed command.

**Comment by NicolasGeraud** [comment]
You don't have to change version inside the dockerfile. Use ``--build-arg`` option of ``docker build``.

**Comment by Tony-Proum** [comment]
Ok thanks, that s a good idea ! Do you think that sed commands could be replaced to be more flexible ? It may be an excellent solution if we have not to change the lines numbers for the parameters.

I have no idea of how to do this, I will take a look when I have a moment. Maybe have you got an idea ?

**Comment by NicolasGeraud** [comment]
Yes, we could use an environment variable in the gravitee.yml
We have to work on that.

**Comment by NicolasGeraud** [comment]
I close this issue 'cause it's based on a feature branch.
Thanks @Tony-Proum for the feedback, the fix will be released in the next version.
