### ISSUE TITLE
Start the script with sh is wrong on linux

### ISSUE THREAD

**Issue by intelradoux** [gravitee-io/gravitee-docker#6]
On linux,   "curl -L http://bit.ly/graviteeiodemo | sh"      is wrong.  (launch the script with sh but some command are bash only like "declare" "echo -e"  ....  )

It should be
curl -L http://bit.ly/graviteeiodemo | bash

**Comment by brasseld** [comment]
Thanks @intelradoux !

If you have a PR for this, you are very welcome !

**Comment by intelradoux** [comment]
Done. Just fixing the doc...

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-docker/pull/7

Thanks a lot @intelradoux !
